#!/bin/bash
# CalOpen one-command Docker setup (Linux / macOS)
# Usage: ./docker-setup.sh
set -e

echo "==============================================="
echo " CalOpen Docker Setup (1 minute)"
echo "==============================================="
echo ""
echo "You need (free):"
echo "  1. Docker: https://docs.docker.com/get-docker/"
echo "  2. Supabase project: https://supabase.com"
echo "     -> Settings > API > Project URL + anon key + service_role key"
echo ""

# 1. Docker check
if ! command -v docker &> /dev/null; then
    echo "ERROR: Docker is not installed."
    echo "Install it from https://docs.docker.com/get-docker/ and re-run."
    exit 1
fi
if ! docker compose version &> /dev/null; then
    echo "ERROR: 'docker compose' not found. Update Docker Desktop."
    exit 1
fi
echo "OK: $(docker --version | head -n1)"
echo ""

# 2. Questions (only the 3 required values; rest is auto-generated)
prompt_default() { # $1=varname $2=prompt $3=default
    local val
    read -p "$2" val
    if [ -z "$val" ]; then val="$3"; fi
    printf -v "$1" '%s' "$val"
}

if [ -f .env ]; then
    read -p ".env already exists. Overwrite? [y/N] " ow
    if [[ ! "$ow" =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env. Starting..."
        docker compose up -d --build
        echo ""
        echo "Open http://localhost:3000"
        exit 0
    fi
fi

echo "--- Supabase (paste from dashboard) ---"
prompt_default SUPABASE_URL "Project URL (https://xyz.supabase.co): " ""
prompt_default SUPABASE_ANON "anon public key (sb_publishable_...): " ""
prompt_default SUPABASE_SERVICE "service_role key (sb_secret_...): " ""

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON" ] || [ -z "$SUPABASE_SERVICE" ]; then
    echo "ERROR: all three Supabase values are required."
    exit 1
fi

echo ""
echo "--- App URL (press Enter for local use) ---"
prompt_default APP_URL "Public URL [http://localhost:3000]: " "http://localhost:3000"

# 3. Auto-generate secrets
if command -v openssl &> /dev/null; then
    DB_PASSWORD=$(openssl rand -hex 24)
    TOKEN_SECRET=$(openssl rand -hex 32)
else
    DB_PASSWORD=$(head -c 48 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 48)
    TOKEN_SECRET=$(head -c 64 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 64)
fi

# 4. Write .env
cat > .env <<EOF
# Generated by docker-setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE}
DB_PASSWORD=${DB_PASSWORD}
BOOKING_TOKEN_SECRET=${TOKEN_SECRET}
NEXT_PUBLIC_APP_URL=${APP_URL}
EMAIL_FROM=CalOpen <onboarding@resend.dev>
EOF

echo ""
echo "Wrote .env (secrets auto-generated)."
echo ""
echo "--- Starting CalOpen ---"
echo "Trying prebuilt image first (fast)..."
if docker compose pull app 2>/dev/null; then
    echo "Prebuilt image pulled."
    docker compose up -d
else
    echo "No prebuilt image yet, building locally (~3-5 min)..."
    docker compose up -d --build
fi

echo ""
echo "==============================================="
echo " Done! Open ${APP_URL}"
echo " Sign up, create an event, share your /book link."
echo " Logs: docker compose logs -f app"
echo " Stop:  docker compose down"
echo "==============================================="
