@echo off
REM CalOpen one-command Docker setup (Windows)
REM Usage: docker-setup.bat
setlocal EnableDelayedExpansion

echo ===============================================
echo  CalOpen Docker Setup (1 minute)
echo ===============================================
echo.
echo You need (free):
echo   1. Docker Desktop: https://docs.docker.com/get-docker/
echo   2. Supabase project: https://supabase.com
echo      -^> Settings ^> API ^> Project URL + anon key + service_role key
echo.

REM 1. Docker check
where docker >nul 2>nul
if errorlevel 1 (
    echo ERROR: Docker is not installed.
    echo Install Docker Desktop and re-run.
    exit /b 1
)
docker compose version >nul 2>nul
if errorlevel 1 (
    echo ERROR: 'docker compose' not found. Update Docker Desktop.
    exit /b 1
)
echo OK: Docker found.
echo.

if exist .env (
    set /p OW=".env already exists. Overwrite? [y/N] "
    if /i not "!OW!"=="y" (
        echo Keeping existing .env. Starting...
        docker compose up -d --build
        echo.
        echo Open http://localhost:3000
        exit /b 0
    )
)

echo --- Supabase (paste from dashboard) ---
set /p SUPABASE_URL="Project URL (https://xyz.supabase.co): "
set /p SUPABASE_ANON="anon public key (sb_publishable_...): "
set /p SUPABASE_SERVICE="service_role key (sb_secret_...): "

if "!SUPABASE_URL!"=="" goto :missing
if "!SUPABASE_ANON!"=="" goto :missing
if "!SUPABASE_SERVICE!"=="" goto :missing
goto :appurl
:missing
echo ERROR: all three Supabase values are required.
exit /b 1

:appurl
echo.
echo --- App URL (Enter for local use) ---
set /p APP_URL="Public URL [http://localhost:3000]: "
if "!APP_URL!"=="" set APP_URL=http://localhost:3000

REM 2. Auto-generate secrets as hex (no special chars, no openssl needed)
for /f %%i in ('powershell -NoProfile -Command "$b = New-Object byte[] 24; (New-Object Random).NextBytes($b); ($b | ForEach-Object { $_.ToString('x2') }) -join ''"') do set DB_PASSWORD=%%i
for /f %%i in ('powershell -NoProfile -Command "$b = New-Object byte[] 32; (New-Object Random).NextBytes($b); ($b | ForEach-Object { $_.ToString('x2') }) -join ''"') do set TOKEN_SECRET=%%i

REM 3. Write .env
(
echo # Generated by docker-setup.bat
echo NEXT_PUBLIC_SUPABASE_URL=!SUPABASE_URL!
echo NEXT_PUBLIC_SUPABASE_ANON_KEY=!SUPABASE_ANON!
echo SUPABASE_SERVICE_ROLE_KEY=!SUPABASE_SERVICE!
echo DB_PASSWORD=!DB_PASSWORD!
echo BOOKING_TOKEN_SECRET=!TOKEN_SECRET!
echo NEXT_PUBLIC_APP_URL=!APP_URL!
echo EMAIL_FROM=CalOpen ^<onboarding@resend.dev^>
) > .env

echo.
echo Wrote .env (secrets auto-generated).
echo.
echo --- Starting CalOpen ---
echo Trying prebuilt image first (fast)...
docker compose pull app >nul 2>nul
if errorlevel 1 (
    echo No prebuilt image yet, building locally ^(about 3-5 min^)...
    docker compose up -d --build
) else (
    echo Prebuilt image pulled.
    docker compose up -d
)

echo.
echo ===============================================
echo  Done - open !APP_URL!
echo  Sign up, create an event, share your /book link.
echo  Logs: docker compose logs -f app
echo  Stop:  docker compose down
echo ===============================================
